### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by Daniil193** [mowshon/age-and-gender#2]
Hello! Help please, I cannot understand what needs to be fixed to solve this error at the installation stage...

running install
running bdist_egg
running egg_info
writing age_and_gender.egg-info\PKG-INFO
writing dependency_links to age_and_gender.egg-info\dependency_links.txt
writing requirements to age_and_gender.egg-info\requires.txt
writing top-level names to age_and_gender.egg-info\top_level.txt
reading manifest file 'age_and_gender.egg-info\SOURCES.txt'
writing manifest file 'age_and_gender.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\username\Documents\FILES\Packages\age_gender\age-and-gender
-- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.18363.
-- pybind11 v2.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/username/Documents/FILES/Packages/age_gender/age-and-gender/build/temp.win-amd64-3.6/Release
Microsoft (R) Build Engine версии 15.8.169+g1ccb72aefa для .NET Framework
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  source.cpp
c:\users\username\documents\files\packages\age_gender\age-and-gender\libs\dlib\dlib\all\../image_loader/png_loader.c
pp(13): fatal error C1083: Не удается открыть файл включение: png.h: No such file or directory, [C:\Users\username\D
ocuments\FILES\Packages\age_gender\age-and-gender\build\temp.win-amd64-3.6\Release\age_and_gender.vcxproj]
Traceback (most recent call last):
  File "setup.py", line 63, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)#, shell=True
  File "C:\Anaconda3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.

**Comment by dakiev** [comment]
The same problem. Did you find solution?

**Comment by mowshon** [comment]
@Daniil193 @dakiev 
https://github.com/go-vgo/robotgo/issues/47

**Comment by Yumi-345** [comment]
> Hello! Help please, I cannot understand what needs to be fixed to solve this error at the installation stage...
> 
> running install
> running bdist_egg
> running egg_info
> writing age_and_gender.egg-info\PKG-INFO
> writing dependency_links to age_and_gender.egg-info\dependency_links.txt
> writing requirements to age_and_gender.egg-info\requires.txt
> writing top-level names to age_and_gender.egg-info\top_level.txt
> reading manifest file 'age_and_gender.egg-info\SOURCES.txt'
> writing manifest file 'age_and_gender.egg-info\SOURCES.txt'
> installing library code to build\bdist.win-amd64\egg
> running install_lib
> running build_ext
> C:\Users\username\Documents\FILES\Packages\age_gender\age-and-gender
> -- Selecting Windows SDK version 10.0.17134.0 to target Windows 10.0.18363.
> -- pybind11 v2.5.0
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/username/Documents/FILES/Packages/age_gender/age-and-gender/build/temp.win-amd64-3.6/Release
> Microsoft (R) Build Engine версии 15.8.169+g1ccb72aefa для .NET Framework
> (C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
> 
> source.cpp
> c:\users\username\documents\files\packages\age_gender\age-and-gender\libs\dlib\dlib\all../image_loader/png_loader.c
> pp(13): fatal error C1083: Не удается открыть файл включение: png.h: No such file or directory, [C:\Users\username\D
> ocuments\FILES\Packages\age_gender\age-and-gender\build\temp.win-amd64-3.6\Release\age_and_gender.vcxproj]
> Traceback (most recent call last):
> File "setup.py", line 63, in build_extension
> subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)#, shell=True
> File "C:\Anaconda3\lib\subprocess.py", line 291, in check_call
> raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.

**Comment by mowshon** [comment]
@Daniil193 @dakiev @Yumi-345 The new version is now available. It can be easily installed using pip.
