### ISSUE TITLE
Problems with installation. returned non-zero exit status 1.

### ISSUE THREAD

**Issue by dakiev** [mowshon/age-and-gender#3]
Hi. Could you help me? 

PS C:\Users\User\Downloads\age-and-gender-master> python setup.py install --user
running install
running bdist_egg
running egg_info
creating age_and_gender.egg-info
writing age_and_gender.egg-info\PKG-INFO
writing dependency_links to age_and_gender.egg-info\dependency_links.txt
writing requirements to age_and_gender.egg-info\requires.txt
writing top-level names to age_and_gender.egg-info\top_level.txt
writing manifest file 'age_and_gender.egg-info\SOURCES.txt'
reading manifest file 'age_and_gender.egg-info\SOURCES.txt'
writing manifest file 'age_and_gender.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:7 (PROJECT):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/User/Downloads/age-and-gender-master/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    setup(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 32, in run
    self.build_extension(ext)
  File "setup.py", line 60, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\User\\Downloads\\age-and-gender-master', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\User\\Downloads\\age-and-gender-master\\build\\lib.win-amd64-3.8\\', '-DPYTHON_EXECUTABLE=C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python38\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\User\\Downloads\\age-and-gender-master\\build\\lib.win-amd64-3.8\\', '-A', 'x64']' returned non-zero exit status 1.

**Comment by mowshon** [comment]
Try this: https://stackoverflow.com/questions/13050827/cmake-problems-specifying-the-compiler

**Comment by mowshon** [comment]
@dakiev The new version is now available. It can be easily installed using pip.
